
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Jul  2 2025 17:06:14 IST (Jul  2 2025 11:36:14 UTC)

// Verification Directory fv/cla_4bit 

module cla_4bit(a, b, cin, sum, cout, pg, gg);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output cout, pg, gg;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire cout, pg, gg;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_13, n_17, n_18, n_19;
  CLKXOR2X1 g416__8780(.A (n_11), .B (n_19), .Y (sum[3]));
  MXI2XL g418__4296(.A (n_4), .B (n_17), .S0 (n_18), .Y (sum[2]));
  OAI21XL g417__3772(.A0 (n_18), .A1 (n_17), .B0 (n_3), .Y (n_19));
  OAI2BB1XL g420__1474(.A0N (cin), .A1N (pg), .B0 (n_13), .Y (cout));
  INVXL g422(.A (n_13), .Y (gg));
  MXI2XL g421__4547(.A (n_7), .B (n_9), .S0 (n_10), .Y (sum[1]));
  AOI222XL g423__9682(.A0 (b[3]), .A1 (a[3]), .B0 (n_0), .B1 (n_8), .C0
       (n_6), .C1 (n_11), .Y (n_13));
  AOI21XL g419__2683(.A0 (n_10), .A1 (n_9), .B0 (n_5), .Y (n_18));
  AND2X1 g426__1309(.A (n_1), .B (n_8), .Y (pg));
  INVXL g424(.A (n_7), .Y (n_9));
  OAI2BB1XL g428__6877(.A0N (n_5), .A1N (n_4), .B0 (n_3), .Y (n_6));
  AND3XL g427__2900(.A (n_11), .B (n_10), .C (n_4), .Y (n_8));
  CLKXOR2X1 g429__2391(.A (cin), .B (n_1), .Y (sum[0]));
  AOI21XL g425__7675(.A0 (cin), .A1 (n_1), .B0 (n_0), .Y (n_7));
  ADDHXL g431__7118(.A (b[1]), .B (a[1]), .CO (n_5), .S (n_10));
  ADDHXL g432__8757(.A (b[0]), .B (a[0]), .CO (n_0), .S (n_1));
  INVXL g430(.A (n_4), .Y (n_17));
  CLKXOR2X1 g433__1786(.A (b[2]), .B (a[2]), .Y (n_4));
  CLKXOR2X1 g434__5953(.A (b[3]), .B (a[3]), .Y (n_11));
  NAND2XL g435__5703(.A (b[2]), .B (a[2]), .Y (n_3));
endmodule

